# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "Company" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"email" VARCHAR NOT NULL,"phone" VARCHAR NOT NULL);
create table "CompanyCustomer" ("customer_id" BIGINT NOT NULL,"company_id" BIGINT NOT NULL,"code" BIGINT NOT NULL);
create table "CompanyProduct" ("product_id" BIGINT NOT NULL,"company_id" BIGINT NOT NULL,"code" BIGINT NOT NULL);
create table "Customer" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"code" BIGINT NOT NULL);
create table "Order" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"customer_id" BIGINT NOT NULL,"product_id" BIGINT NOT NULL,"status_id" INTEGER NOT NULL,"price" DOUBLE NOT NULL,"created" DATE NOT NULL,"updated" DATE NOT NULL);
create table "Product" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"code" BIGINT NOT NULL,"name" VARCHAR NOT NULL,"price" DOUBLE NOT NULL);
create table "Status" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL);
create table "User" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"name" VARCHAR NOT NULL,"company_id" BIGINT);
create unique index "idx_email" on "User" ("email");
alter table "Order" add constraint "customer_fk" foreign key("customer_id") references "Customer"("id") on update NO ACTION on delete NO ACTION;
alter table "Order" add constraint "product_fk" foreign key("product_id") references "Product"("id") on update NO ACTION on delete NO ACTION;
alter table "Order" add constraint "status_fk" foreign key("status_id") references "Status"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "Order" drop constraint "customer_fk";
alter table "Order" drop constraint "product_fk";
alter table "Order" drop constraint "status_fk";
drop table "User";
drop table "Status";
drop table "Product";
drop table "Order";
drop table "Customer";
drop table "CompanyProduct";
drop table "CompanyCustomer";
drop table "Company";

